### ISSUE TITLE
About Dataset.

### ISSUE THREAD

**Issue by XZhang00** [zjwang21/MoE-LPR#1]
Hi, thanks for your excellent and solid work!

For the dataset used in the two stages, could you share the sample code or other details to help reproduce the results?

Looking forward to your reply!

**Comment by zjwang21** [comment]
LLaMA-Factory/tools/count_tokens.py gives an example about how to generate training tokens. 

For stage1, we concatenated the first 30 parquet files in each language of CulturaX [https://huggingface.co/datasets/uonlp/CulturaX](url) and shuffle it to save in one json file. Then use the count_tokens.py to collect whatever number of tokens. For stage2, we use the first n samples of the json file.

**Comment by XZhang00** [comment]
I sincerely thank you for the reply.
